### ISSUE TITLE
Discovered incompatibility issue with dependency libraries (pitaya/v2->etcd ->grpc) when updating dependencies

### ISSUE THREAD

**Issue by chengroot** [topfreegames/pitaya#369] opened 2023-11-27 06:21 UTC
Hello everybody !!
    When I upgraded Pitaya to v2.8.0 and used the go mod tidy command, a test dependency error occurred: "finding module for package google.golangorg/grpc/test/grpc_testing"
    Error screenshot:
![图片](https://github.com/topfreegames/pitaya/assets/31918286/7b8bddd4-b6a5-42cb-bdd8-15a4b52819cf)

operating system: windows 10.
go version: 1.21.4
The main dependencies are shown in the figure：
![图片](https://github.com/topfreegames/pitaya/assets/31918286/e186f7d3-9adb-4a30-964e-fbb15afe7956)

**Comment by chengroot** [comment] 2023-11-28 02:40
Thank you, the issue disappeared after the replacement. Looking forward to the next version ！

**Comment by rsafonseca** [comment] 2023-12-07 17:51
Hi @chengroot 
The problem is now fixed in v2.8.1, you can remove the replace directive and update and you shouldn't have any problems with the grpc dependencies :)

**Closed** 2023-12-12 09:16 UTC
